const { Pool } = require('pg');
const pool = require('./dbConn');

pool.query(`INSERT INTO creature (name, ac, hp, stre, dex, cons, intel, wis, charisma, chal, attack, special, description, mon_img) VALUES
('Aarakocra', 12, 13, 10, 14, 10, 11, 12, 11, 1/4, '{Talon: Melee Weapon Attack +4 to hit reach 5 ft. one target. Hit 4 (1d4 + 2) slashing damage.,	Javelin: Melee or Ranged Weapon Attack +4 to hit reach 5 ft. or range 30/120 ft. one target. Hit 5 (1d6 + 2) piercing damage.}', '{Dive Attack: If the aarakocra is flying and dives at least 30ft straight toward a target and then hits it with a melee weapon attack the attack deals an extra 3 (1d6) damage to the target., Bite (Ex): When grounded an aarakocra attacks with its beak (+1 melee) dealing 1d3 points of damage on a successful attack., Summon Large Air Elemental (Su): Five aarakocra within 30 feet of each other can magically summon an air elemental. Each of the five must use its action and movement on three consecutive turns to perform an aerial dance and must maintain concentration while doing so (as if concentrating on a spell). When all five have finished their third turn of the dance the elemental appears in an unoccupied space within 60ft of them. It is friendly toward them and obeys their spoken commands. It remains for 1 hour until it or all its summoners die or until any of its summoners dismisses it as a bonus action. A summoner can not perform the dance again until it finishes a short rest. When the elemental returns to the Elemental Plane of Air any aarakocra within 5 feet of it can return with it.}', 'Aarakocra are bird-like humanoids with feathers and a beak. Their hands have three fingers and a thumb and they also have a pair of feathered wings. Aarakocra have lean legs ending in talons. Aarakocra look like large birds from below until they land. Aarakocra have advantage on saving throws against lightning and thunder damage as well as against spells or powers that manipulate air such as gust of wind wind wall or an air elementals whirlwind power. Aarakocra have lean lightweight bodies typically 80 to 100 pounds. Their skeletons are hollow and fragile. Their wings anchor in a bony chest plate that provides some slight natural protection.', 'https://www.dndbeyond.com/avatars/thumbnails/7/622/420/618/636286750209394240.png'),
('Aboleth',	17, 135, 21, 9,	15,	18,	15,	18,	10,	'{Multiattack: The aboleth makes three tentacle attacks., Tentacle: Melee Weapon Attack +9 to hit reach 10ft. one target. Hit: 12 (2d6 + 5) bludgeoning damage. If the target is a creature it must succeed on a DC 14 Constitution saving throw or become diseased. The disease has no effect for 1 minute and can be removed by any magic that cures disease. After 1 minute the diseased creatures skin becomes translucent and slimy the creature can not regain hit points unless it is underwater and the disease can be removed only by heal or another disease-curing spell of 6th level or higher. When the creature is outside a body of water, it takes 6 (1d12) acid damage every 10 minutes unless moisture is applied to the skin before 10 minutes have passed., Tail: Melee Weapon Attack +9 to hit reach 10ft. one target. Hit 15 (3d6 + 5) bludgeoning damage., Enslave (3/Day): The aboleth targets one creature it can see within 30 feet of it. The target must succeed on a DC 14 Wisdom saving throw or be magically charmed by the aboleth until the aboleth dies or until it is on a different plane of existence from the target. The charmed target is under the aboleths control and can not take reactions and the aboleth and the target can communicate telepathically with each other over any distance. Whenever the charmed target takes damage the target can repeat the saving throw. On a success the effect ends. No more than once every 24 hours the target can also repeat the saving throw when it is at least 1 mile away from the aboleth.}', '{Detect: The aboleth makes a Wisdom (Perception) check, Tail Swipe: The aboleth makes one tail attack., Psychic Drain: (Costs 2 Actions) One creature charmed by the aboleth takes 10 (3d6) psychic damage and the aboleth regains hit points equal to the damage the creature takes.}', 'Aboleth underbellies were often orange-pink while their topsides were typically sea-green. A little bit back from the head were four long tentacles two sprouting from across each other on the top and two more of the same on the underbelly. Their heads were roughly triangular-shaped with a spherical somewhat beak-like nose. Above the nose were their three eyes each one set atop the other. Tendrils and a few shorter tentacles dangled from the bottom of the head.', 'https://www.dndbeyond.com/avatars/thumbnails/30761/774/1000/1000/638061093283829548.png'),
('Animated Object Armor', 18, 33, 14, 22, 23, 1, 3, 11,	1, '{Multiattack: The armor makes two melee attacks., Slam: The creature batters opponents with an appendage dealing bludgeoning damage., Melee Weapon Attack: +4 to hit reach 5 ft. one target. Hit 5 (ld6 + 2) bludgeoning damage.}', '{Antimagic Susceptibility: The armor is incapacitated while in the area of an anti magic field. If targeted by dispel magic the armor must succeed on a Constitution saving throw against the casters spell save DC or fall unconscious for 1 minute.,	False Appearance: While the armor remains motion less it is indistinguishable from a normal suit of armor.}', 'This empty steel shell clamors as it moves heavy plates banging and grinding against one another like the vengeful spirit of a fallen knight. Ponderous but persistent, this magical guardian is almost always a suit of plate armor.', 'https://www.dndbeyond.com/avatars/thumbnails/31312/506/1000/1000/638084408333616236.png'),
('Animated Object Flying Sword', 17, 17, 12, 15, 11, 1, 5, 1, 1/4, '{Longsword: Melee Weapon Attack +3 to hit, reach 5ft., one target. Hit 5(1d8 + 1) slashing damage.}', '{Antimagic Susceptibility: The sword is incapacitated while in the area of an anti magic field. if targeted by dispel magic the sword must succeed on a Constitution saving throw against the casters spell save DC or fall unconscious for 1 minute, False Appearance: While the sword remains motionless and is not flying it is indistinguishable from a normal sword.}', 'Swords are the most common weapons animated with magic. Axes clubs daggers maces spears and even selfloading crossbows are also known to exist in animated object form.', 'https://www.dndbeyond.com/avatars/thumbnails/30761/834/1000/1000/638061095632921781.png')`,
        (err, data) => {
            if(err){
                console.log("Insert failed");
            }else{
                console.log(results);
            }
        });

//close connection
pool.end();